/**
 * Reveal Match (G1), ported from Aryan's Flutter `reveal_match`.
 * Original design: Aryan.
 *
 * All rules live in `./model`, which is pure TypeScript and separately
 * tested. This file is rendering, timing and event emission only.
 *
 * | Event | Payload | When |
 * |---|---|---|
 * | `card_revealed` | `{cardId}` | a card is turned face-up by a tap |
 * | `pair_resolved` | `{attemptId, matched, cardIds}` | the second card of an attempt |
 * | `board_cleared` | — | every pair has been found |
 *
 * Plus the shared lifecycle events through the recorder: `session_started`,
 * `hint_requested`, `paused`, `resumed`, `session_finished`.
 *
 * `cardId` and `asset` are opaque ids generated by the model. A picture's
 * label never enters a payload — there is a test asserting it.
 *
 * A mismatch emits `pair_resolved {matched: false}` and shows the patient
 * nothing: the two cards simply turn back over. No cross, no sound, no count.
 */
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, fontScaleCaps, spacing } from '../../design/tokens';
import { GameScaffold } from '../GameScaffold';
import { EmptyBoard, GameLayout, Settle, tileVisual } from '../presentation';
import {
  GameResultStatus,
  TesseractEventRecorder,
  gameText,
  type GameItem,
  type TesseractGameProps,
} from '../contract';
import {
  REVEAL_MATCH_COLUMNS,
  RevealMatchBoard,
  buildDeck,
  revealMatchDifficultyParams,
} from './model';

export const REVEAL_MATCH_ID = 'reveal_match';
export { revealMatchDifficultyParams };

/** How often the resolution deadline is checked. Cheap and imprecise on purpose. */
const SETTLE_TICK_MS = 120;

export function RevealMatchGame({ config, onEvent, onFinish }: TesseractGameProps) {
  const recorder = useRef(new TesseractEventRecorder()).current;
  const params = useMemo(
    () => revealMatchDifficultyParams(config.level),
    [config.level],
  );

  /** Content, keyed by the opaque asset id the model deals in. */
  const itemsByAsset = useMemo(() => {
    const map = new Map<string, GameItem>();
    for (const item of config.items) map.set(item.id, item);
    return map;
  }, [config.items]);

  const board = useMemo(() => {
    const assets = config.items.map((i) => i.id);
    if (new Set(assets).size < params.pairCount) return null;
    return new RevealMatchBoard(buildDeck(assets, params.pairCount), params);
  }, [config.items, params]);

  const [, forceRender] = useState(0);
  const redraw = useCallback(() => forceRender((n) => n + 1), []);

  const [paused, setPaused] = useState(false);
  const [hintedPairId, setHintedPairId] = useState<string | null>(null);
  const started = useRef(false);
  const done = useRef(false);

  if (!started.current) {
    started.current = true;
    onEvent(recorder.sessionStarted());
    if (config.isTutorial) onEvent(recorder.tutorialStarted());
  }

  const finish = useCallback(
    (status: 'completed' | 'stopped_by_user') => {
      if (done.current) return;
      done.current = true;
      onEvent(recorder.sessionFinished(status));
      onFinish(recorder.result(status));
    },
    [onEvent, onFinish, recorder],
  );

  /**
   * Drives the mismatch resolution deadline.
   *
   * A timer rather than a render loop, and it reads the recorder's clock so a
   * pause genuinely suspends the countdown. It also does no layout work — the
   * only thing it can do is clear the selection and ask for one redraw.
   */
  useEffect(() => {
    if (!board || paused || done.current) return;
    const id = setInterval(() => {
      if (!board.settle(recorder.elapsedMs)) return;
      redraw();
      if (board.isComplete) {
        onEvent(recorder.custom('board_cleared'));
        if (config.isTutorial) onEvent(recorder.tutorialCompleted());
        finish(GameResultStatus.completed);
      }
    }, SETTLE_TICK_MS);
    return () => clearInterval(id);
  }, [board, paused, recorder, redraw, onEvent, finish, config.isTutorial]);

  const pause = useCallback(() => {
    setPaused(true);
    onEvent(recorder.paused());
  }, [onEvent, recorder]);

  const resume = useCallback(() => {
    setPaused(false);
    onEvent(recorder.resumed());
  }, [onEvent, recorder]);

  const stop = useCallback(() => {
    setPaused(false);
    finish(GameResultStatus.stoppedByUser);
  }, [finish]);

  /** Help names one unfound pair. It never plays the move for the patient. */
  const help = useCallback(() => {
    if (!board) return;
    onEvent(recorder.hintRequested());
    const unfound = board.allCards.find((c) => !board.isMatched(c.id));
    setHintedPairId(unfound?.pairId ?? null);
    redraw();
  }, [board, onEvent, recorder, redraw]);

  const tap = useCallback(
    (cardId: string) => {
      if (!board || paused || done.current) return;
      const outcome = board.tap(cardId, recorder.elapsedMs);
      if (!outcome.accepted) return;

      onEvent(recorder.custom('card_revealed', { cardId }));

      if (outcome.resolved) {
        const { matched, cardIds, attemptNumber } = outcome.resolved;
        onEvent(
          recorder.custom('pair_resolved', {
            attemptId: `attempt-${attemptNumber}`,
            matched,
            cardIds,
          }),
        );
        if (matched) setHintedPairId(null);
      }
      redraw();
    },
    [board, paused, recorder, onEvent, redraw],
  );

  const scaffold = (children: React.ReactNode, helpEnabled = true) => (
    <GameScaffold
      strings={config.strings}
      paused={paused}
      helpEnabled={helpEnabled}
      onHelp={help}
      onBreak={pause}
      onResume={resume}
      onFinishNow={stop}
    >
      {children}
    </GameScaffold>
  );

  if (!board) {
    // Too few distinct pictures to build even one honest pair. Say so rather
    // than reusing a picture and making two cards that cannot be told apart.
    return scaffold(
      <EmptyBoard text={gameText(config.strings, 'reveal_unavailable')} />,
      false,
    );
  }

  const preview = board.previewVisible;

  return scaffold(
    <GameLayout
      prompt={gameText(config.strings, 'reveal_find_the_pair')}
      subPrompt={
        preview ? gameText(config.strings, 'reveal_preview_hint') : undefined
      }
      boardAspect={params.pairCount >= 4 ? 1.05 : 0.85}
      board={(size) => {
        const gap = 12;
        const cell = (size - gap * (REVEAL_MATCH_COLUMNS - 1)) / REVEAL_MATCH_COLUMNS;
        return (
          <View style={[styles.grid, { gap }]}>
            {board.allCards.map((card) => {
              const faceUp = board.isFaceUp(card.id);
              const matched = board.isMatched(card.id);
              const hinted = !matched && card.pairId === hintedPairId;
              const visual = tileVisual(
                matched ? 'done' : hinted ? 'hinted' : 'idle',
              );
              const item = itemsByAsset.get(card.asset);
              const label = item?.label ?? '';

              return (
                <Settle key={card.id} trigger={`${faceUp}-${matched}`}>
                  <Pressable
                    accessibilityRole="button"
                    // Face-down cards must not leak their picture to a screen
                    // reader, or the game is solvable without looking.
                    accessibilityLabel={
                      faceUp
                        ? label
                        : gameText(config.strings, 'reveal_hidden_card')
                    }
                    accessibilityState={{ disabled: matched || preview }}
                    disabled={matched || preview || paused}
                    onPress={() => tap(card.id)}
                    style={({ pressed }) => [
                      styles.card,
                      {
                        width: cell,
                        height: cell,
                        backgroundColor: faceUp ? visual.bg : colors.peach,
                        borderColor: faceUp ? visual.border : colors.hairline,
                        borderWidth: faceUp ? visual.width : 1.5,
                      },
                      pressed && !matched && styles.pressed,
                    ]}
                  >
                    {faceUp ? (
                      <Text
                        numberOfLines={2}
                        maxFontSizeMultiplier={fontScaleCaps.buttonLabel}
                        style={[styles.face, { color: visual.fg }]}
                      >
                        {label}
                      </Text>
                    ) : (
                      // A calm back, not a question mark: nothing here should
                      // read as a quiz the patient might fail.
                      <View style={styles.back} />
                    )}
                  </Pressable>
                </Settle>
              );
            })}
          </View>
        );
      }}
    >
      {preview ? (
        <Pressable
          accessibilityRole="button"
          accessibilityLabel={gameText(config.strings, 'reveal_ready')}
          onPress={() => {
            board.dismissPreview();
            redraw();
          }}
          style={({ pressed }) => [styles.ready, pressed && styles.pressed]}
        >
          <Text
            maxFontSizeMultiplier={fontScaleCaps.buttonLabel}
            style={styles.readyLabel}
          >
            {gameText(config.strings, 'reveal_ready')}
          </Text>
        </Pressable>
      ) : null}
    </GameLayout>,
  );
}

const styles = StyleSheet.create({
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  card: {
    borderRadius: spacing.cardRadius,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  pressed: { opacity: 0.8 },
  face: { fontSize: 20, fontWeight: '700', textAlign: 'center' },
  back: {
    width: '55%',
    height: '55%',
    borderRadius: 999,
    backgroundColor: colors.white,
    opacity: 0.55,
  },
  ready: {
    minHeight: spacing.patientTarget,
    borderRadius: 999,
    backgroundColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    marginTop: 8,
  },
  readyLabel: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.white,
    textAlign: 'center',
  },
});
