"""initial schema

Revision ID: 9592999903e3
Revises: 
Create Date: 2026-09-07 21:26:59.461247
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9592999903e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('known_type', sa.String(length=64), nullable=True),
    sa.Column('known_stage', sa.String(length=64), nullable=True),
    sa.Column('accessibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_uid', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('caregiver', 'doctor')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_uid'), 'users', ['auth_uid'], unique=True)
    op.create_table('activity_settings',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('input_mode', sa.String(length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('caregiver_patients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('owner', 'member')", name='ck_caregiver_patients_role'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'patient_id')
    )
    op.create_table('doctor_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_user_id', 'patient_id', name='uq_doctor_assignment')
    )
    op.create_table('doctor_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_notes_patient_id'), 'doctor_notes', ['patient_id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('generator', sa.String(length=32), nullable=False),
    sa.Column('generator_version', sa.String(length=32), nullable=False),
    sa.Column('source_session_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_reports_patient_id'), 'generated_reports', ['patient_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'content_sha256', name='uq_media_patient_content')
    )
    op.create_index(op.f('ix_media_assets_patient_id'), 'media_assets', ['patient_id'], unique=False)
    op.create_table('personal_words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=128), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_words_patient_id'), 'personal_words', ['patient_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('source_session_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('proposed_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('based_on_config_version', sa.Integer(), nullable=False),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending', 'accepted', 'modified', 'rejected', 'expired', 'superseded')", name='ck_recommendations_status'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_patient_id'), 'recommendations', ['patient_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule_version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_patient_id'), 'reminders', ['patient_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('game_id', sa.String(length=64), nullable=False),
    sa.Column('game_version', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('config_version', sa.String(length=16), nullable=False),
    sa.Column('content_version', sa.String(length=16), nullable=False),
    sa.Column('metric_version', sa.String(length=16), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('difficulty_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_input_mode', sa.String(length=16), nullable=False),
    sa.Column('actual_input_mode', sa.String(length=16), nullable=False),
    sa.Column('input_mode_unverified', sa.Boolean(), nullable=False),
    sa.Column('is_tutorial', sa.Boolean(), nullable=False),
    sa.Column('assisted', sa.Boolean(), nullable=False),
    sa.Column('text_scale', sa.Float(), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('final_seq', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("actual_input_mode in ('touch', 'tilt')", name='ck_sessions_actual_input'),
    sa.CheckConstraint("requested_input_mode in ('touch', 'tilt')", name='ck_sessions_requested_input'),
    sa.CheckConstraint("status in ('open', 'completed', 'stopped_by_user', 'interrupted')", name='ck_sessions_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_patient_game', 'sessions', ['patient_id', 'game_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sessions_patient_id'), 'sessions', ['patient_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('elapsed_ms >= 0', name='ck_events_elapsed_non_negative'),
    sa.CheckConstraint('seq >= 1', name='ck_events_seq_positive'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_events_session_seq')
    )
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_table('known_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('person', 'place')", name='ck_known_entries_kind'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_known_entries_patient_id'), 'known_entries', ['patient_id'], unique=False)
    op.create_table('reminder_occurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reminder_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schedule_version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('acknowledgement_state', sa.String(length=32), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("acknowledgement_state is null or acknowledgement_state in ('acknowledged', 'postponed', 'cancelled')", name='ck_occurrence_ack_state'),
    sa.CheckConstraint("state in ('scheduled', 'prompted', 'cancelled')", name='ck_occurrence_state'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_id', 'scheduled_for', name='uq_occurrence_reminder_time')
    )
    op.create_index(op.f('ix_reminder_occurrences_patient_id'), 'reminder_occurrences', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reminder_occurrences_reminder_id'), 'reminder_occurrences', ['reminder_id'], unique=False)
    op.create_table('session_metrics',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('metric_version', sa.String(length=16), nullable=False),
    sa.Column('calculator_id', sa.String(length=64), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unavailable', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_metrics')
    op.drop_index(op.f('ix_reminder_occurrences_reminder_id'), table_name='reminder_occurrences')
    op.drop_index(op.f('ix_reminder_occurrences_patient_id'), table_name='reminder_occurrences')
    op.drop_table('reminder_occurrences')
    op.drop_index(op.f('ix_known_entries_patient_id'), table_name='known_entries')
    op.drop_table('known_entries')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_sessions_patient_id'), table_name='sessions')
    op.drop_index('ix_sessions_patient_game', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_reminders_patient_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_recommendations_patient_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_personal_words_patient_id'), table_name='personal_words')
    op.drop_table('personal_words')
    op.drop_index(op.f('ix_media_assets_patient_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_generated_reports_patient_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_doctor_notes_patient_id'), table_name='doctor_notes')
    op.drop_table('doctor_notes')
    op.drop_table('doctor_assignments')
    op.drop_table('caregiver_patients')
    op.drop_table('activity_settings')
    op.drop_index(op.f('ix_users_auth_uid'), table_name='users')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
